[package]
name = "snake-rs"
version = "0.1.0"
authors = ["limit <limitliu@qq.com>"]
edition = "2018"

[dependencies]
rand = "0.7"

[dependencies.sdl2]
version = "0.37"
default-features = false
features = ["ttf", "image", "gfx", "mixer"]
